// å

const words = [
  ["fösta", "première"],
  ["andra", "deuxième"],
  ["tredje", "troisième"],
  ["fjärde", "quatrième"],
  ["femte", "cinquième"],
  ["lektionen", "leçon"],
  ["bra bättre bäst", "bien"],
  ["du", "tu"],
  ["fråg/a -an -or", "question"],
  ["fröken", "mademoiselle/maîtresse"],
  ["ha (hava) -r -de -haft", "avoir"],
  ["hej", "bonjour"],
  ["hur", "comment"],
  ["idag", "aujourd'hui"],
  ["men", "mais"],
  ["må -r -dde -tt", "aller (se porter)"],
  ["tack", "merci"],
  ["då", "alors"],
  ["gift", "marié(e)"],
  ["heta/a -er hette hetat", "s'appeler"],
  ["igår", "hier"],
  ["ja", "oui"],
  ["lilla (liten)", "petit"],
  ["som", "comme"],
  ["vara är var varit", "être"],
  ["varför", "pourquoi"],
  ["viktig", "important"],
  ["tredge", "troisième"],
  ["morgon", "matin"],
  ["imorgon", "demain"],
  ["dag", "jour/journée"],
  ["det", "ça ce"],
  ["dig", "toi"],
  ["god gottgoda", "bon"],
  ["godmorgon", "bonjour(matin)"],
  ["goddag", "bonjour (formel)"],
  ["grej -en -er", "machin truc"],
  ["går", "hier"],
  ["hon", "elle"],
  ["inte", "ne... pas"],
  ["jätt/e -ar -en", "géant"],
  ["jätte", "archi vachement"],
  ["jättebra", "super"],
  ["jättelitten", "minuscule"],
  ["jätteviktig", "archi-important"],
  ["kär", "amoureux"],
  ["morgon -en mor(g)nar", "matiné"],
  ["sov/a -er sov sovit", "dormir"],
  ["vad", "comment, que, quoi, combien, qu'est-ce que, ce que"],
  ["vilken vilket vilka", "quel quelle quels quelles"],
  ["äta äter åt ätit", "manger"],
  ["alltså", "donc"],
  ["diska -r -de -t", "vaiselle (faire la)"],
  ["dusch -en -ar", "douche"],
  ["där", "là-bas"],
  ["hallå", "allo"],
  ["han", "il"],
  ["hej då", "salut (au revoir)"],
  ["komma kommer kom kommit", "arriver venir"],
  ["mustasch -en -en", "moustache"],
  ["nej", "non"],
  ["nisch", "niche"],
  ["och", "et"],
  ["okej", "ok"],
  ["ring/a -er -de -t", "sonner téléphoner"],
  ["telefon -en -er", "téléphone"],
  ["tjänare", "salut (serviteur)"],
  ["älskling", "chéri/e"],
  ["ett", "un/e"],
  ["glas -et", "verre"],
  ["kosta -r -de -t", "coûter"],
  ["kött -et", "viande"],
  ["lax -en -ar", "saumon"],
  ["mjölk -en", "lait"],
  ["skiv/a -an -or", "tranche"],
  ["skort/a -an -or", "chemise"],
  ["vin -et -er", "vin"],
];

export default words;
