// å

const words = [
  ["fösta", "première"],
  ["bra", "bien"],
  ["du", "tu"],
  ["fråga", "question"],
  ["fröken", "mademoiselle/maîtresse"],
  ["ha -r", "avoir"],
  ["hej", "bonjour"],
  ["hur", "comment"],
  ["idag", "aujourd'hui"],
  ["men", "mais"],
  ["må -r", "aller (se porter)"],
  ["tack", "merci"],
  ["då", "alors"],
  ["gift", "marié(e)"],
  ["heta/a -er", "s'appeler"],
  ["igår", "hier"],
  ["ja", "oui"],
  ["lilla (liten)", "petit"],
  ["som", "comme"],
  ["vara är var varit", "être"],
  ["varför", "pourquoi"],
  ["viktig", "important"],
  ["tredge", "troisième"],
  ["morgon", "matin"],
  ["imorgon", "demain"],
  ["dag", "jour/journée"],
  ["det", "ça ce"],
  ["dig", "toi"],
  ["god gottgoda", "bon"],
  ["godmorgon", "bonjour(matin)"],
  ["goddag", "bonjour (formel)"],
  ["grej -en -er", "machin truc"],
];

export default words;
